# Accent canonicalization mapping
# Maps various free-text accent labels to standardized names

mappings:
  # American
  american:
    - american
    - united states
    - us
    - usa
    - en-us
    - america
  
  # British
  british:
    - british
    - england
    - uk
    - united kingdom
    - en-gb
    - gb
    - scottish
    - scotland
    - wales
    - welsh
  
  # Indian
  indian:
    - indian
    - india
    - en-in
  
  # African
  african:
    - african
    - africa
    - south african
    - south africa
    - nigerian
    - nigeria
    - kenyan
    - kenya
  
  # Australian
  australian:
    - australian
    - australia
    - en-au
  
  # Irish
  irish:
    - irish
    - ireland
  
  # Canadian
  canadian:
    - canadian
    - canada
    - en-ca

# Minimum samples required per accent to include it
min_samples_threshold: 100

